# Generated by Django 5.2 on 2025-04-12 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('courses', '0004_course_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='courses',
            field=models.ManyToManyField(to='courses.course'),
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
