# Generated by Django 5.2 on 2025-04-12 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cart_courses_delete_cartitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='student',
            new_name='user',
        ),
    ]
