# Generated by Django 5.2 on 2025-04-13 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsa_assignments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dsaassignment',
            name='difficulty',
            field=models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], default='Easy', max_length=10),
        ),
    ]
